### ISSUE TITLE
PLEASE READ THIS FIRST! : Known issue

### ISSUE THREAD

**Issue by SteveKunG** [SteveKunG/More-Planets#1]
Please post your crash report if you found crashes.

[Known issues]
GC Map conflict with Koentus Moon (Like the same as other GC add-on.)
Radiation Effect crash with Custom Mod Pack

If you found crash like this.

Description: Ticking entity
java.lang.NullPointerException: Ticking entity
at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:229)
at stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket.func_70071_h_(EntityTier8Rocket.java:80)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at WorldServerOF.func_72870_g(WorldServerOF.java:347)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

This is dimension conflict with other mod. Please changing my mod Dimension IDs, I recommended to settings dimension ids to -200+.

**Comment by Glitchyminecraft** [comment]
Solid meteoric iron blocks can not be crafted into ingots. is it intended or a bug?.

**Comment by SteveKunG** [comment]
Hm? I don't know. Please tell to Galacticraft author. Not my mod, Thanks!

**Comment by Glitchyminecraft** [comment]
i mean metal meteoric iron

**Comment by SteveKunG** [comment]
I already tested. It work fine.

**Comment by rtatro20** [comment]
i got this error :P ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/3/15 3:49 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:229)
	at stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket.func_70071_h_(EntityTier8Rocket.java:87)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:229)
	at stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket.func_70071_h_(EntityTier8Rocket.java:87)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: MorePlanet.Tier8Rocket (stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket)
	Entity ID: 160187
	Entity Name: entity.MorePlanet.Tier8Rocket.name
	Entity's Exact location: -2161.50, 8.15, -1068.50
	Entity's Block location: World: (-2162,8,-1069), Chunk: (at 14,0,3 in -136,-67; contains blocks -2176,0,-1072 to -2161,255,-1057), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Whalegax'/52, l='New World', x=-2161.50, y=8.40, z=-1068.50]]
	Chunk stats: ServerChunkCache: 290 Drop: 0
	Level seed: 3628616126999806821
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 2;2x4,3x3,2;1;village,biome_1
	Level spawn location: World: (-2167,4,-1071), Chunk: (at 9,0,1 in -136,-67; contains blocks -2176,0,-1072 to -2161,255,-1057), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025)
	Level time: 1270 game time, 1270 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 111249 (now: false), thunder time: 53315 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 140567688 bytes (134 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 37, allocated: 2, tallocated: 28
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.0} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	modJ_StarMinerCore{0.9.9} [StarMinerCore] (minecraft.jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) 
	UCHIJAAAA	securitycraft{v1.7.4.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.7.4.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.7.12B} [Moving World] (movingworld-1.7.10-1.7.12B.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.7.10-1.7.12} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.7.12.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.29.1.75} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.29.1.75.jar) 
	UCHIJAAAA	examplemod{1.0} [Example Mod] (Avatar TLB 0.7.4.jar) 
	UCHIJAAAA	kieranvs_avatar{0.7.4} [Avatar] (Avatar TLB 0.7.4.jar) 
	UCHIJAAAA	babyanimals{1.7.10-2} [Baby Animals Model Swapper] (BabyAnimals-1.7.10-2.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar) 
	UCHIJAAAA	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.4b} [Extra Utilities] (extrautilities-1.2.4b.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333 (1).jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	modJ_StarMiner{0.9.9} [Starminer Mod] (Starminer1710-0.9.9.jar) 
	UCHIJAAAA	modJ_JointBlock{0.2.0} [JointBlock] (JointBlock1710-0.2.0.jar) 
	UCHIJAAAA	modJ_JBRobot{0.1.0} [JBRobotModel] (JBRobotModel1710-0.1.0.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	MorePlanet{1.2.9} [More Planets] (More-Planets-1.7.10-1.2.9.jar) 
	UCHIJAAAA	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-2} [PortalGun] (PortalGun-4.0.0-beta-2.jar) 
	UCHIJAAAA	ProjRed|Core{4.4.5.44} [ProjectRed] (ProjectRed-Base-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration] (ProjectRed-World-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility] (ProjectRed-Compat-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	ProjRed|Integration{4.4.5.44} [ProjectRed-Integration] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination] (ProjectRed-Lighting-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) 
	UCHIJAAAA	SmartMoving{15.1} [Smart Moving] (SmartMoving-1.7.10-15.1.jar) 
	UCHIJAAAA	SmartRender{2.0} [Smart Render] (SmartRender-1.7.10-2.0.jar) 
	UCHIJAAAA	Squicken{1.0.0} [Squicken] (Squicken-1.7-1.0.0.jar) 
	UCHIJAAAA	SpecialArmor{1.7.10} [TeeLuk's SpecialArmor] (TLSpecialArmor-1.7.10.jar) 
	UCHIJAAAA	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) 
	UCHIJAAAA	wearmc{1.7.10g} [WearMC] (WearMC-Forge-1.7.10g.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Whalegax'/52, l='New World', x=-2161.50, y=8.40, z=-1068.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by demenslayer** [comment]
what is the new update for Galacticraft

**Comment by jonabrv1965** [comment]
Hi Best! just a quick question (I do not know if its a bug). I use quarries to mine planets and got tons of ores, but this ores seems not be recognized by my Buildcraft miners robots. According to Buildcraft developers, the ores must by registered in a Ore Dictionary to be detected... any idea?
Nonetheless your mod is awesome!!! very good work!!!

**Comment by SteveKunG** [comment]
Buildcraft Miner Robot is using Ore Dictionary to find ores?

**Comment by jonabrv1965** [comment]
Yep! : http://mod-buildcraft.com/forums/showthread.php?tid=1792

**Comment by SteveKunG** [comment]
Thank you, I will registering my ores to Ore Dictionary in the next version. Thanks again!

**Comment by jonabrv1965** [comment]
You welcome, I just found another mod that does not work with your "nonregistered" ores : nuclear craft.... better hurry with the inclusion! ;-)

**Comment by challenger1** [comment]
So I changed the Dimension IDs, but now I am getting this error: 
http://paste.ubuntu.com/12198781/
Am I just supposed to change the Koenetus Moon dimension, or is there something else I'm supposed to do?

**Comment by SteveKunG** [comment]
You are changing my mod dimension ids to -200+? I think id -21 is not my mod setting by default.

**Comment by challenger1** [comment]
Yes, I just left all of the dimensions at their default number, but subracted 200. So dimension -7 became dimension -207. The closest ones I have to dimension -21 are dimensions -221 and -212.

**Comment by SteveKunG** [comment]
It's not working? You are tries to set -400 or less than -400?

**Comment by SteveKunG** [comment]
@jonabrv1965 I adding Ore Dictionary to the my block. Thanks for suggestion.
See at : https://github.com/SteveKunG/More-Planets/commit/90c3d88f8970fc1b9e902d88d7aea0a3ff609c45
